services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: #TODO: find best practice
    volumes:
      - ./data:/data #TODO: find proper way to mount volume
    ports:
      - 432:5432

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 80:8080
    depends_on:
      - db

  orm:
    container_name: ORM
    build: /scripts/backend/database/.
    depends_on:
      - db

  frontend:
    container_name: GUI
    build: /scripts/frontend/.
    depends_on:
      - orm

  functions:
    container_name: functions
    build: /scripts/backend/functions/.